### ISSUE TITLE
提示以下报错

### ISSUE THREAD

**Issue by Nu-Exception** [Jacen789/rolling-news#2]
invalid syntax (<string>, line 1)
downloading http://www.sohu.com/a/834964805_122014422
Error reading file 'http://www.sohu.com/a/834964805_122014422': failed to load external entity "http://www.sohu.com/a/834964805_122014422"
downloading http://www.sohu.com/a/834964452_255783
Error reading file 'http://www.sohu.com/a/834964452_255783': failed to load external entity "http://www.sohu.com/a/834964452_255783"
downloading http://www.sohu.com/a/834964445_119778
Error reading file 'http://www.sohu.com/a/834964445_119778': failed to load external entity "http://www.sohu.com/a/834964445_119778"
downloading http://www.sohu.com/a/834964173_120596020
Error reading file 'http://www.sohu.com/a/834964173_120596020': failed to load external entity "http://www.sohu.com/a/834964173_120596020"
downloading http://www.sohu.com/a/834963035_121284943
Error reading file 'http://www.sohu.com/a/834963035_121284943': failed to load external entity "http://www.sohu.com/a/834963035_121284943"
downloading http://www.sohu.com/a/834961573_260616
Error reading file 'http://www.sohu.com/a/834961573_260616': failed to load external entity "http://www.sohu.com/a/834961573_260616"
downloading http://www.sohu.com/a/834959912_121997544
Error reading file 'http://www.sohu.com/a/834959912_121997544': failed to load external entity "http://www.sohu.com/a/834959912_121997544"
downloading http://www.sohu.com/a/834964455_162818
Error reading file 'http://www.sohu.com/a/834964455_162818': failed to load external entity "http://www.sohu.com/a/834964455_162818"
downloading http://www.sohu.com/a/834921757_115362
Error reading file 'http://www.sohu.com/a/834921757_115362': failed to load external entity "http://www.sohu.com/a/834921757_115362"
downloading http://www.sohu.com/a/834917848_120988533
Error reading file 'http://www.sohu.com/a/834917848_120988533': failed to load external entity "http://www.sohu.com/a/834917848_120988533"
downloading http://www.xinhuanet.com/fortune/2021-07/23/c_1127684495.htm
Document is empty
downloading http://www.xinhuanet.com/fortune/2021-07/20/c_1127672423.htm
Document is empty
downloading http://www.xinhuanet.com/fortune/2021-07/14/c_1127654394.htm
Document is empty
downloading http://www.xinhuanet.com/fortune/2021-07/08/c_1127634257.htm
Document is empty
downloading http://www.xinhuanet.com/fortune/2021-07/01/c_1127615427.htm
Document is empty
downloading http://www.xinhuanet.com/fortune/2021-06/30/c_1127612172.htm
Document is empty
downloading http://www.xinhuanet.com/fortune/2021-06/29/c_1127608119.htm
Document is empty
downloading http://www.xinhuanet.com/fortune/2021-06/28/c_1127603712.htm
Document is empty
downloading http://www.xinhuanet.com/fortune/2021-01/07/c_1126956627.htm
Document is empty
downloading http://www.xinhuanet.com/fortune/2021-01/04/c_1126945553.htm
Document is empty
Traceback (most recent call last):
File "D:\Python\NewsCrawler-master\main.py", line 18, in <module>
news_crawler.save_news(sina_news_df, os.path.join(news_path, 'sina_latest_news.csv'))
File "D:\Python\NewsCrawler-master\utils\news_crawler.py", line 177, in save_news
news_df.to_csv(path, index=False, encoding='gb18030')
^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'to_csv'

**Comment by Jacen789** [comment]
这应该是我的另一个仓库的代码报的错。你自己去对应的网站找新的入口吧。
爬取搜狐的，你只需要改一下代码，使用requests库先获取网页内容，然后再用lxml解析。
```python
def latest_content(net, url):
    """
    获取即时财经新闻内容
    :param net: 指定网站名
    :param url: 新闻链接
    :return: string
        返回新闻的文字内容
    """
    content = ''
    try:
        # 使用requests获取页面内容
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
        }
        response = requests.get(url, headers=headers, timeout=10)
        response.encoding = 'utf-8'
        
        # 使用lxml解析内容
        html = lxml.html.fromstring(response.text)
        res = html.xpath(xpaths[net])
        p_str_list = [etree.tostring(node).strip().decode('utf-8') for node in res]
        content = '\n'.join(p_str_list)
        html_content = lxml.html.fromstring(content)
        content = html_content.text_content()
        content = re.sub(r'(\r*\n)+', '\n', content)
    except Exception as e:
        print(f"获取内容失败: {url}")
        print(f"错误信息: {str(e)}")
    return content
```
